PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX efo: <http://www.ebi.ac.uk/efo/>
PREFIX atlas: <http://rdf.ebi.ac.uk/resource/atlas/>
PREFIX atlasterms: <http://rdf.ebi.ac.uk/terms/atlas/>

SELECT distinct ?expUri ?expressionValue ?expressionRatioClass ?dbXref ?pvalue ?tstat ?disease
WHERE {
    ?expUri atlasterms:hasAnalysis ?analysis ;
        atlasterms:isAbout obo:NCBITaxon_9606.
    ?analysis atlasterms:hasExpressionValue ?value .
    ?value a ?expressionRatioClass .
    ?value rdfs:label ?expressionValue .
    ?value atlasterms:tStatistic ?tstat.
    ?value atlasterms:pValue ?pvalue .
    ?value atlasterms:isMeasurementOf ?probe .
    ?value atlasterms:hasFactorValue ?factor .
    ?probe atlasterms:dbXref ?dbXref .
    ?factor atlasterms:propertyType ?propertyType.
    ?factor a ?disease.
    ?dbXref a atlasterms:UniprotDatabaseReference.

    filter(?disease == owl:NamedIndividual)
    filter(?foo == ?bar)
    filter(?owl:sameAs == ?quux)
}